# Generated by Django 3.2.9 on 2022-03-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20220322_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paylog',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
